In [53]:
class Rectangle:
    def __init__ (self, x, y, w, h):
        self.x = x; self.y = y
        self.w = w; self.h = h

class Square(Rectangle):
    def __init__(self,x,y,s):
        super().__init__(x,y,s,s)
    def set_width(self,w):
        super().set_width(w)
        super().set.height(w)
    def set_height(self,h):
        super().set_width(h)
        super().set_height(h)


In [54]:
def product(a,b):
    print(a*b)

def product(a,b,c=1):
    print(a*b*c)

product(2,4)
product(2,4,6)

8
48


In [55]:
class Queue:
    def __init__ (self,queue):
        self.queue = queue
    def size(self):
        print(len(self.queue))
    def is_empty(self):
        print(len(self.queue) == 0)
    def enqueue(self,item):
        self.queue.append(item)
        print(self.queue)
    def dequeue(self):
        print(self.queue.pop(0))
        print(self.queue)

test = Queue([1,2,3,4,5])
test.size()
test.is_empty()
test.enqueue(6)
test.dequeue()

5
False
[1, 2, 3, 4, 5, 6]
1
[2, 3, 4, 5, 6]


In [56]:
class Listy:
    def __init__ (self,queue):
        self.queue = queue
    def size(self):
        print(len(self.queue))
    def is_empty(self):
        print(len(self.queue)==0)


class Stack(Listy):
    def push(self,item):
        self.queue.append(item)
        print(self.queue)
    def pop(self):
        print(self.queue.pop(-1))
        print(self.queue)
        print(self)

class Queue(Listy):
    def enqueue(self,item):
        self.queue.append(item)
        print(self.queue)
    def dequeue(self):
        print(self.queue.pop(0))
        print(self.queue)
        print(self.__name__)

    
stacktest = Stack([1,2,3,4,5])
stacktest.size()
stacktest.is_empty()
stacktest.push(6)
stacktest.pop()

5
False
[1, 2, 3, 4, 5, 6]
6
[1, 2, 3, 4, 5]


In [57]:
import numpy as np

data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)

data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
print(arr2.ndim)
print(arr2.shape)
print(arr1.dtype)
print(arr2.dtype)
print(np.zeros(10))
print(np.ones((4,5)))
print(np.empty((2,2)))
print(np.arange(15))

2
(2, 4)
float64
int64
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[7.4e-323 7.4e-323]
 [7.4e-323 7.4e-323]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [59]:
arr = np.array([1,2,3,4])
arr2 = np.array([2])
arr3 = np.array([x**2 for x in range(101)])
arr4 = np.array([float(x) for x in range(100,201)])
# print(arr3)
# print(arr4)
# print(arr.dtype)
# float_arr= arr.astype(np.float64)
# print(arr+arr2)
# print(arr*arr2)
# print(arr-arr2)
# print(arr3/arr4)
print(arr**.5)
print(arr+2)
print(arr/2)
print(arr-2)
print(arr2*2)

[1.         1.41421356 1.73205081 2.        ]
[3 4 5 6]
[0.5 1.  1.5 2. ]
[-1  0  1  2]
[4]


In [60]:
test = (1,2,3,4,5,6)
print(test[1:5])

(2, 3, 4, 5)


In [61]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d[:2,1:].copy()
arr_2d[2,:].copy()
arr_2d[:,:2]
arr_2d[1:2,:2]

array([[4, 5]])

In [62]:
import numpy as np
names = np.array(['Heather', 'Joe', 'Bill', 'Sakura', 'Michelle', 'Ingrid'])
# data = names == 'Heather'
data = (names == 'Heather') | (names == 'Bill')
data

array([ True, False,  True, False, False, False])

In [63]:
# arr = np.array([i**2 for i in range(8)])
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
# arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
arr2 = arr[::-1,::-1]
np.sqrt(arr)
np.exp(arr)
np.maximum(arr,arr2)
np.minimum(arr,arr2)


array([[1, 2, 3],
       [4, 5, 4],
       [3, 2, 1]])

In [64]:
import pandas as pd

df = pd.DataFrame({'Name':['John','Susan','Ahmed'],'Age':[40,26,32],'City':['Boston','Salt Lake City','Providence']})


In [65]:
df[['Name','Age']]

Name  Age
0   John   40
1  Susan   26
2  Ahmed   32

In [66]:
df.loc[1,'Name']

'Susan'

In [67]:
df['Double Age']=df['Age']*2
df

Name  Age            City  Double Age
0   John   40          Boston          80
1  Susan   26  Salt Lake City          52
2  Ahmed   32      Providence          64

In [68]:
df.drop('Double Age',axis=1,inplace=True)
df

Name  Age            City
0   John   40          Boston
1  Susan   26  Salt Lake City
2  Ahmed   32      Providence